name: pcm_mobile_app
description: "He thong quan ly CLB Pickleball Vo Thu Pho Nui"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  dio: ^5.9.0
  provider: ^6.1.5+1
  flutter_secure_storage: ^10.0.0
  signalr_netcore: ^1.3.5
  intl: ^0.20.2
  image_picker: ^1.0.7
  table_calendar: ^3.2.0
  fl_chart: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true